# Generated by Django 4.1.9 on 2023-06-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_first_name_user_last_name_alter_user_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sku", models.CharField(max_length=12, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("price", models.PositiveBigIntegerField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("A", "Administrator"), ("M", "Manager"), ("P", "Product")], default="A", max_length=1
            ),
            preserve_default=False,
        ),
    ]
