# Generated by Django 4.1.9 on 2023-06-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_product_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(choices=[("A", "Adminstrator"), ("M", "Manager")], default="M", max_length=1),
        ),
    ]
