# Generated by Django 4.1.9 on 2023-06-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
